/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package edu.curtin.comp3003.TextEditor.core;

import java.util.Locale;
import java.util.ResourceBundle;

import javafx.application.Application;
import javafx.scene.control.TextArea;
import javafx.stage.Stage;



public class App extends Application
{
    public static void main(String[] args)
    {
        Application.launch(args);
    }

    @Override
    public void start(Stage stage)
    {
        ResourceBundle bundle;
        var localeString = getParameters().getNamed().get("locale");
        
        if(localeString != null && localeString.contains("-"))
        {
            String[] split = localeString.split("-");
            
            if(split.length == 2)
            {
                // Specified language property to be used
                Locale locale1 = new Locale(split[0], split[1]);
                bundle = ResourceBundle.getBundle("bundle", locale1);
                System.out.println("Using locale bundle");
            }
            else // Default language properties used
            {
                bundle = ResourceBundle.getBundle("bundle");
            }
        }
        else // Default language properties used
        {
            bundle = ResourceBundle.getBundle("bundle");
        }
        
        TextArea textArea = new TextArea();
        FileIO fileIO = new FileIO();
        LoadSaveUI loadSaveUI = new LoadSaveUI(stage, bundle, fileIO, textArea);
        new MainUI(stage, bundle, loadSaveUI, textArea).display();
    }
    
    
}

